### ISSUE TITLE
'seed' command should default to reporting the current seeds

### ISSUE THREAD

**Issue by jgreely** [matthew-humphrey/nmssavetool#14]
In version 2.0.1-beta, `seed -g 1` sets ship seed to 0x0000000000000000.

What I expected it to do was give me help text about the missing -c and -r/-s options.

What I'd like it to do is report the values of the current seeds.

Print all seeds:
    `seed -g 1`

Print active ship seed (and type):
    `seed -g 1 -c ship`

Alternatively, the current seeds could be added to the `info` output.

**Comment by matthew-humphrey** [comment]
Thank you very much for catching this. I have fixed the bug, and added the display current value feature as you suggest, both to info and the seed command itself. Also, as an FYI, the program was setting the seed correctly, just not displaying it correctly. So it was not set to "0x0" and your seed value should still be there. You can grab the updated binaries here:
https://github.com/matthew-humphrey/nmssavetool/releases/tag/v2.0.1.4-beta-2

**Comment by jgreely** [comment]
Works great, thanks.
