### ISSUE TITLE
Support for the GOG version?

### ISSUE THREAD

**Issue by Moonbane** [matthew-humphrey/nmssavetool#17]
Is it possible to add support for the GOG version of the game?
My save game files are located in C:\Users\username\AppData\Roaming\HelloGames\NMS\DefaultUser
When I run nmssavetool the output is:

D:\nmssavetool-2.0.1.4-beta-2>nmssavetool refurbish -g 1 -c ship
No save game profile folder found in NMS save game folder: C:\Users\username\AppData\Roaming\HelloGames\NMS

However when I create a bogus Steam subfolder st_12345678901234567 in C:\Users\username\AppData\Roaming\HelloGames\NMS\ and copy the save files there (mf_save.hg, mf_save2.hg, save.hg, save2.hg) the tool appears to work correctly:

D:\nmssavetool-2.0.1.4-beta-2>nmssavetool refurbish -g 1 -c ship
Refurbished items in the following inventory groups: ship.
Wrote latest game save for game slot "1"

Win 7, Game version: GOG v1.38

**Comment by matthew-humphrey** [comment]
Thanks for reporting this bug. There was already support for GoG in there, but the change to the save game file names in NMS 1.38 broke the detection of the GOG save directory. I've fixed that bug and created an updated release here:
https://github.com/matthew-humphrey/nmssavetool/releases/tag/v2.0.1.5-beta-3

Can you please give it a try and let me know if it's resolved for you?

**Comment by Moonbane** [comment]
Hi,
I was out in the boonies and it took me a while to be able to board my freighter to test things :-)
nmssavetool-2.0.1.5-beta-3 correctly identified GOG's saved games folder.

nmssavetool refurbish -g 1 did not refill exosuit cargo inventory substance slots and did not recharge starship hyperdrive.

nmssavetool recharge -g 1 did not recharge starship hyperdrive and multi-tool technology.

nmssavetool refill -g 1 refilled everything.
nmssavetool repair -g 1 repaired everything.

Thank you for this awesome tool!

**Comment by matthew-humphrey** [comment]
Thank you! I created a new issue, #19 to track the separate issues you found with refurbish and recharge.
