### ISSUE TITLE
Refurbish and recharge commands not updating all inventory groups

### ISSUE THREAD

**Issue by matthew-humphrey** [matthew-humphrey/nmssavetool#19]
(Forked from issue #17 reported by user @Moonbane )

nmssavetool refurbish -g 1 did not refill exosuit cargo inventory substance slots and did not recharge starship hyperdrive.

nmssavetool recharge -g 1 did not recharge starship hyperdrive and multi-tool technology.

**Comment by matthew-humphrey** [comment]
Fixed in version 2.0.1.6 (beta-4)
https://github.com/matthew-humphrey/nmssavetool/releases/tag/v2.0.1.6-beta-4

**Comment by Moonbane** [comment]
Thanks for the fixes! nmssavetool v2.0.1.6 beta 4 works perfectly! Great work, man!

**Comment by matthew-humphrey** [comment]
You're welcome. Thanks for finding the issue and verifying the fix.
