### ISSUE TITLE
Enhancement to Modify?

### ISSUE THREAD

**Issue by temp-999** [matthew-humphrey/nmssavetool#2]
I'm currently on NMS 1.31.
Windows 10 Pro 1607
Everything is working fine! I use the Decrypt, Encrypt and Modify -a.

Would you consider adding more functionality to Modify? 

Additional Inventory locations: 
Storage Containers 0-9 - Chest1Inventory through Chest10Inventory
Exosuit has a new Cargo area - Inventory_Cargo

Other refillable stuff that's there but not important (to me):
Exocrafts have Inventory/Technology areas
Exosuit has a new area for Tech - Inventory_TechOnly
Freighter has a new area for Tech - FreighterInventory_TechOnly (doesn't seem to be working currently)
Starships have a new area for Tech - Inventory_TechOnly (may not be working currently)

**Comment by matthew-humphrey** [comment]
Hi -

I've already added support for the new inventory areas (ship, exosuit) in NMS 1.3, but they are currently only in a branch dev/nms_1_3, as I haven't released them yet.  Currently there is no support for storage containers, but I will take a look at that and see if it is something I can fit into this upcoming release.

I'd really like to add a feature to fill any open inventory slot with an item of choice. But I need to go through the list of inventory codes, and come up with the appropriate human readable (English only, for now) versions of those, and that's quite a bit of tedious work. If anyone who wants to contribute such a list (hint hint), I would be glad to add the feature.

**Comment by matthew-humphrey** [comment]
I added support for storage containers, so everything you requested should be there. You can grab the pre-release version here:

https://github.com/matthew-humphrey/nmssavetool/releases/download/v1.4.3-pre/nmssavetool-1.4.3-pre.zip

**Comment by temp-999** [comment]
Hi, You're extremely quick! I grabbed the 1.4.3-pre release and will test today. I try to maintain an Excel spreadsheet of the Substance, Product, and Technology items. NMS 1.3 has added a lot of new ones and I haven't found them all. Would something like this be of use to you?ACCESS1,Atlas Pass v1
ACCESS2,Atlas Pass v2
ACCESS3,Atlas Pass v3
ACID,Acid
ALBUMENPEARL,Albumen Pearl
ALLOY1,Aronium
ALLOY2,Herox
ALLOY3,Lemmium
ALLOY4,
ALLOY5,
ALLOY6,
ALLOY7,Terumin
ALLOY8, 

---------- Original Message ----------

**Comment by temp-999** [comment]
Tried the Modify -a and got this:  C:\Users\<me>\Desktop\Test_Folder>C:\Users\<me>\Desktop\Test_Folder\nmssavetool-1.4.3-pre\nmssavetool.exe modify -a -g normal -v
CLR version: 4.0.30319.42000
APPDATA folder: C:\Users\<me>\AppData\Roaming
Reading latest normal-mode save game file from:
 C:\Users\<me>\AppData\Roaming\HelloGames\NMS\st_<###mine>\storage3.hg
Error loading or parsing save file: Could not load file or assembly 'SpookilySharp, Version=1.1.5126.40896, Culture=neutral, PublicKeyToken=317149717b49a330' or one of its dependencies. The system cannot find the file specified. I copied SpookilySharp.dll and SpookilySharp.xml from the old folder into the new and it ran great!
____________________________________________________________
After Weeks Of Rumors, Joanna Gaines Comes Clean
trecommanews.com
http://thirdpartyoffers.juno.com/TGL3131/59949f7575b761f753304st03vuc

**Comment by matthew-humphrey** [comment]
Oh, good catch on the missing DLL. I will fix that when I get home this evening. 

The CSV format for the items is perfect. Maybe we should share that on one of the NMS Wiki's so that others could contribute to it?

**Comment by matthew-humphrey** [comment]
I uploaded a new release zip file (same name and release number). Would you mind giving it a try?

**Comment by temp-999** [comment]
The latest release has everything and worked fine! I'm going to work on the missing descriptions for the new items.  
____________________________________________________________
After Weeks Of Rumors, Joanna Gaines Comes Clean
trecommanews.com
http://thirdpartyoffers.juno.com/TGL3131/5994cac8685f14ac82ff7st02vuc

**Comment by temp-999** [comment]
I'm sometimes getting:  C:\Users\<me>\Desktop\Test_Folder>encrypt -g normal -v -i C:\Users\<me>\Desktop\Test_Folder\decrypted.json
DNS server not authoritative for zone. 
____________________________________________________________
Actress Tells All: "I Felt Bloated, Tired...Now I Know Why"
ActivatedYou
http://thirdpartyoffers.juno.com/TGL3131/5994d5404636553f6e5dst03vuc

**Comment by temp-999** [comment]
Never mind - found my error. 
____________________________________________________________
Police Urge Americans to Carry This With Them at All Times
The Observer
http://thirdpartyoffers.juno.com/TGL3131/5994d7de29b0b57de194dst02vuc

**Comment by temp-999** [comment]
Do you want Substance and/or Product and/or Technology items? 
____________________________________________________________
How To Remove Eye Bags & Lip Lines Fast (Watch)
Fit Mom Daily
http://thirdpartyoffers.juno.com/TGL3131/5994f293c8b84729339e0st01vuc

**Comment by matthew-humphrey** [comment]
Substance is the most important, followed by Product. Ideally your list should give the type.

**Comment by temp-999** [comment]
I put a zipped folder here:  http://dropcanvas.com/0D0mlkyL2Efr89      Files are .cvs but will open with Notepad.


____________________________________________________________
Actress Tells All: "I Felt Bloated, Tired...Now I Know Why"
ActivatedYou
http://thirdpartyoffers.juno.com/TGL3131/5995089ed124989e4b84st02vuc

**Comment by matthew-humphrey** [comment]
This is great. From where did you get the list? The reason I ask is that one of the other Reddit users gave me some instructions to extract the code list (just the codes - not the human readable strings, unfortunately). Might be a good check to see if there are any we missed?

Or maybe we should just provide these files along with the utility. That way any that are missing could quickly be updated - no code update required. 

Thoughts?

**Comment by temp-999** [comment]
I think that I started with the ones that were in my save file a long time ago. Since then I've added more that I've found and from other people's list.     The current Product list going around includes plants and building items. I don't include these in my list because I'll never need them as an inventory item (they're not salable) since once they're in the Known list they become available.      Wouldn't hurt to have someone else QA my lists.     Is there anywhere that you announce updates to your save tool?


 
____________________________________________________________
1 "Trick Ends" Toenail Fungus - Try It Today!
Wellness Above All
http://thirdpartyoffers.juno.com/TGL3131/59950f8a2f160f892ff7st02vuc

**Comment by matthew-humphrey** [comment]
Yes, I have been updating the post here for each new release: https://www.reddit.com/r/NoMansSkyMods/comments/5lhl07/nmssavetool_save_game_editor_version_11/

**Comment by temp-999** [comment]
Tried your link as I thought it would be a better place to discuss the items. However, your post has been archived and I cannot respond there. I've sent the Moderator a message to see if it can be un-archived but haven't heard back yet. Also if I search there for  "No Man's Sky Save Tool", it's not found. 

In the meantime, Substances:
GAS1	Sulphurine
GAS2	Radon
GAS3	Nitrogen

**Comment by matthew-humphrey** [comment]
Ok, thanks for letting me know. I'll start a new post on Reddit once I have the inventory populate feature working. 

Also, for the item codes, I'll move these to a Google doc, and share the link.

**Comment by temp-999** [comment]
Product:

TRA_COMMODITY1	Decrypted User Data
TRA_ENERGY1	                Spark Canister
REACTION3                     Ammonium Salt

**Comment by matthew-humphrey** [comment]
If it's convenient, can you make  your updates to this shared Google Docs spreadsheet?
https://docs.google.com/spreadsheets/d/15mj19FZ76_NWp7TTb-c9QgWWdv3Zv1UQG0s77Zjxpsg/edit?usp=sharing

**Comment by temp-999** [comment]
Will do!


____________________________________________________________
Police Urge Americans to Carry This With Them at All Times
The Observer
http://thirdpartyoffers.juno.com/TGL3131/5999cdf8e06f84df855e9st02vuc

**Comment by matthew-humphrey** [comment]
All features you requested are in the 2.0.0 release.
