### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jaszhix** [matthew-humphrey/nmssavetool#4]
Hi, I've been using your tool a lot, and have incorporated the binary in my own project. Its a great tool and I appreciate your effort making it. I was wondering if you could clarify the license so I can be sure everything is in the clear. Thanks!

**Comment by matthew-humphrey** [comment]
Thanks for bringing this up. I thought I had selected a license when I set up the repo, but apparently not. I went ahead and added a LICENSE file to the repo (MIT license). 

BTW - what is your project?

**Comment by jaszhix** [comment]
That's perfect, thanks. It is [No Man's Connect](https://github.com/jaszhix/NoMansConnect), an app that's focused on allowing players to teleport to locations, describe them, and make it easier to meet up. It really wouldn't have been possible without a headless CLI utility like this, so I owe much of its existence to this. 

I attempted to convert the save signing for the metadata header to JS, but JS only supports signed 32 bit integers and the tests I wrote to check my work kept failing.

Anyway, thanks a lot for making this.

**Comment by matthew-humphrey** [comment]
Do you have a good reference on how the coordinate system in the game save file works? Some time back I read a bunch of Reddit threads on it, but there was mixed and ambiguous information out there. I never found a good reference.

**Comment by jaszhix** [comment]
Yeah, this [thread](https://www.reddit.com/r/NoMansSkyTheGame/comments/4yr5e3/galactic_coordinates/) helped me a little bit. I couldn't find an easy way to convert voxel coordinates to the hex format because either nobody had tried or didn't document it, so it resulted in a lot of trial and error before I settled on [this function](https://github.com/jaszhix/NoMansConnect/blob/2343079f2db7524fe07f99467d19b0c5435207e3/app/utils.js#L89) that produces accurate coordinates. I call it in [app.js](https://github.com/jaszhix/NoMansConnect/blob/2343079f2db7524fe07f99467d19b0c5435207e3/app/app.js#L1057) inside the root component, which probably has too much business logic in it.

The ranges for hex coordinates as integers are:
X, Z: -2048 - 2047
Y: -128 - 127

as voxel coordinates:
X, Z: 0 - 4096
Y: 0 - 256

I use [this function](https://github.com/jaszhix/NoMansConnect/blob/2343079f2db7524fe07f99467d19b0c5435207e3/app/utils.js#L134) to convert the hex coordinates back to voxel coordinates where I [experimentally](https://github.com/jaszhix/NoMansConnect/blob/2343079f2db7524fe07f99467d19b0c5435207e3/app/app.js#L925) enable people to teleport to coordinates by spawning them in space by setting the ```LastKnownPlayerState``` to ```InShip```.

I probably should do a better job documenting (and writing) the application, but I often times don't have time, but if you have any other questions I don't mind.

**Comment by jaszhix** [comment]
Really, I cringe looking at some of it, like the convertInteger function could be boiled down to a much simpler [function I meant to replace it with](https://github.com/jaszhix/NoMansConnect/blob/2343079f2db7524fe07f99467d19b0c5435207e3/app/utils.js#L494), but didn't bother because I didn't want to risk regressions. Its a learning process as always. :)

**Comment by matthew-humphrey** [comment]
Thanks, this is great. If you don't mind me adapting that code, I would like to add an option to nmssavetool to set the position.

**Comment by jaszhix** [comment]
Not at all, feel free to adapt anything.
